[package]
name = "nfido"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

log = "0.4.0"
tera = "1.8"
env_logger = "0.8.3"
actix-web = "3"
actix-http = "2.2.0"