[package]
name = "nfido"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

log = "0.4.14"
tera = "1.15.0"
env_logger = "0.9.0"
actix-web = "4.0.1"
actix-http = "3.0.4"
actix-files = "0.6.0"